"""change_embedding_dim_384_to_768

Revision ID: 3cc8ec39d563
Revises: f2d8bbd134d1
Create Date: 2026-03-03 18:53:36.007568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc8ec39d563'
down_revision: Union[str, Sequence[str], None] = 'f2d8bbd134d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documentchunk DROP COLUMN embedding")
    op.execute("ALTER TABLE documentchunk ADD COLUMN embedding vector(3072) NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documentchunk DROP COLUMN embedding")
    op.execute("ALTER TABLE documentchunk ADD COLUMN embedding vector(768) NOT NULL")
    # ### end Alembic commands ###
