"""change_embedding_dim_3072_to_768

Revision ID: 7f24723edf5c
Revises: 94fa472ae583
Create Date: 2026-03-03 20:33:17.673233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f24723edf5c'
down_revision: Union[str, Sequence[str], None] = '94fa472ae583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documentchunk DROP COLUMN embedding")
    op.execute("ALTER TABLE documentchunk ADD COLUMN embedding vector(768) NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documentchunk DROP COLUMN embedding")
    op.execute("ALTER TABLE documentchunk ADD COLUMN embedding vector(3072) NOT NULL")
    # ### end Alembic commands ###
