"""change_embedding_dim_768_to_3072

Revision ID: 94fa472ae583
Revises: 3cc8ec39d563
Create Date: 2026-03-03 20:24:13.104519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fa472ae583'
down_revision: Union[str, Sequence[str], None] = '3cc8ec39d563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documentchunk DROP COLUMN embedding")
    op.execute("ALTER TABLE documentchunk ADD COLUMN embedding vector(3072) NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE documentchunk DROP COLUMN embedding")
    op.execute("ALTER TABLE documentchunk ADD COLUMN embedding vector(768) NOT NULL")
    # ### end Alembic commands ###
